ontologies:
    baseURI: http://opensilex.dev/
    baseURIAlias: dev
    sparql:
        rdf4j:
            serverURI: http://localhost:8667/rdf4j-server/
            repository: opensilex

file-system: 
    storageBasePath: ../../opensilex-data

big-data:   
    nosql:
        mongodb:
            host: localhost
            port: 8668
            database: opensilex

phisws:
    infrastructure: opensilex